[package]
name = "runes24"
version = "1.0.0"
description = "Runes Circle"
authors = [ "Ruslan Prakapchuk <fer.obbee@gmail.com>" ]
license = "MIT"
edition = "2021"
build = "src/build.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
dirs = "6"
snap = "1.1"
tauri = { version = "2", features = [] }

[profile.release]
panic = "abort"
codegen-units = 1
lto = "thin"
incremental = false
opt-level = "s"
