[package]
name = "runes24"
version = "1.0.0"
description = "Runes 24"
authors = [ "Ruslan Prakapchuk <fer.obbee@gmail.com>" ]
license = "Apache-2.0 OR MIT"
edition = "2021"
build = "src/build.rs"

[build-dependencies]
tauri-build = "1.0.0-beta.4"

[dependencies]
dirs = "4.0.0"
serde = { version = "1.0.132", features = [ "derive" ] }
tauri = { version = "1.0.0-beta.8", features = ["api-all"] }
# tauri = { git = "https://github.com/tauri-apps/tauri", branch = "next", features = ["api-all"] }

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"
